### ISSUE TITLE
运行示例的模型预测报错：text_classifier_fscore_focal_loss is not a registered name for Model

### ISSUE THREAD

**Issue by viemsr** [nutalk/allennlp_classification#2]
#### 你好 ，我用`model_lstm.json`配置训练示例数据成功后，运行模型预测部分时：
```
python -m allennlp.service.server_simple --archive-path ./test_double2/model.tar.gz --predictor text_classifier --include-package AllenFrame.data --title "文
本分类" --field-name sentence
```
#### 报错
```
allennlp.common.checks.ConfigurationError: 'text_classifier_fscore_focal_loss is not a registered name for Model. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choi
ces using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly.'

```
json文件中的除路径部分，我都没有更改

#### 另外：用`model_cnn.json`训练示例数据时，一切正常，但是用我的数据
则会报错
`RuntimeError: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size`
当我启用停顿词时报错:
`RuntimeError: Calculated padded input size per channel: (0). Kernel size: (2). Kernel size can't be greater than actual input size`

**Comment by nutalk** [comment]
第一个问题可能是你运行的目录有问题，应该在项目跟目录运行这段命令，不能在example目录运行。
第二个问题是textcnn的特点，你用的文本分词之后的词的数量不能少于kernel的最大size，给一个空文本给他模型会报错。

**Comment by viemsr** [comment]
> 
> 
> 第一个问题可能是你运行的目录有问题，应该在项目跟目录运行这段命令，不能在example目录运行。
> 第二个问题是textcnn的特点，你用的文本分词之后的词的数量不能少于kernel的最大size，给一个空文本给他模型会报错。

#### 谢谢您的解答，第一个问题的话 我是在项目的根目录运行命令的。全部报错信息如下：
```
(venv) D:\Users\viem\PycharmProjects\untitled\qax\allennlp_classification>python -m allennlp.service.server_simple --archive-path ./test_double/model.tar.gz --predictor text_classifier --include-package AllenFrame.data --title "文本
分类" --field-name sentence
_jsonnet not loaded, treating C:\Users\viems\AppData\Local\Temp\tmp0cm8wu4k\config.json as json
Traceback (most recent call last):
  File "C:\Users\viems\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\viems\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Users\viem\PycharmProjects\untitled\venv\lib\site-packages\allennlp\service\server_simple.py", line 758, in <module>
    main(sys.argv[1:])
  File "d:\Users\viem\PycharmProjects\untitled\venv\lib\site-packages\allennlp\service\server_simple.py", line 182, in main
    predictor = _get_predictor(args)
  File "d:\Users\viem\PycharmProjects\untitled\venv\lib\site-packages\allennlp\service\server_simple.py", line 146, in _get_predictor
    overrides=args.overrides)
  File "d:\Users\viem\PycharmProjects\untitled\venv\lib\site-packages\allennlp\models\archival.py", line 230, in load_archive
    cuda_device=cuda_device)
  File "d:\Users\viem\PycharmProjects\untitled\venv\lib\site-packages\allennlp\models\model.py", line 327, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "d:\Users\viem\PycharmProjects\untitled\venv\lib\site-packages\allennlp\common\registrable.py", line 97, in by_name
    raise ConfigurationError(f"{name} is not a registered name for {cls.__name__}. "
allennlp.common.checks.ConfigurationError: 'text_classifier_fscore_focal_loss is not a registered name for Model. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choi
ces using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly.'
```
第二个问题我检查数据看看 是不是哪里给空了。

**Comment by nutalk** [comment]
`--include-package AllenFrame.data`

改成 

`--include-package AllenFrame`

**Comment by viemsr** [comment]
> 
> 
> `--include-package AllenFrame.data`
> 
> 改成
> 
> `--include-package AllenFrame`

可以了 十分感谢！！！
预测的句子长度 ，有办法将其加长吗
